import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthBootstrap } from "@/components/auth-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: "Wevioo",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthBootstrap />
        {children}
      </body>
    </html>
  );
}
