import "./globals.css";
import type { Metadata } from "next";
import { AuthBootstrap } from "@/components/auth-bootstrap";

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: "Wevioo Consulting - Digital - Iot",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const themeScript = `
    (function() {
      try {
        var savedTheme = localStorage.getItem("theme");
        var theme = savedTheme === "dark" || savedTheme === "light"
          ? savedTheme
          : (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
        document.documentElement.classList.toggle("dark", theme === "dark");
      } catch (error) {}
    })();
  `;

  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="font-sans antialiased">
        <AuthBootstrap />
        {children}
      </body>
    </html>
  );
}
